### ISSUE TITLE
Missing metalsmith.json

### ISSUE THREAD

**Issue by jmslbam** [RobinThrift/metalsmith-tutorial#1]
Senior, thank you very much for the tutorial! You are the only one :+1: 
 I have been setting it up and walked into this little bugger here: `Metalsmith · could not find a "metalsmith.json" configuration file.`
So I added this:

```
{
  "source": "src/content",
  "destination": "build",
  "metadata": {
    "title": "Personal website of Jaime Martinez",
    "description": "Whoop whhop"
  },
  "plugins": {
    "metalsmith-markdown": {},
    "metalsmith-permalinks": {
      "pattern": ":title"
    },
    "metalsmith-templates": {
      "engine": "handlebars"
    }
  }
}
```

And then it gave `Metalsmith · The partial header could not be found`.
I am searching for some more resources where I can find what I should do, but this is the only thing that I could find: https://github.com/segmentio/metalsmith-templates/issues/3

Could you help me a bit more? Thanks in advanced!

Jaime

**Comment by joaoafrmartins** [comment]
https://github.com/segmentio/metalsmith-metadata

**Comment by jmslbam** [comment]
Sorry @joaoafrmartins not sure how that one will help me. Care to enlighten me?

**Comment by joaoafrmartins** [comment]
the metalsmith.json file is only loaded when you call metalsmith from the command line last time i checked... but its a small project... take a look at the code

**Comment by RobinThrift** [comment]
@jmslbam , @joaoafrmartins is correct, the metalsmith.json is only called when you run the `metalsmith` CLI, which we are not doing in the tutorial. We use the JavaScript API to build our project, but you could use the JSON varaiant.
